//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.0
//     from Assets/_Game/Scripts/Runtime/Managers/InputManager/SystemInput/PlayerInput/PlayerMovementInputWithoutKeyBoard.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerMovementInputWithoutKeyBoard: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerMovementInputWithoutKeyBoard()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerMovementInputWithoutKeyBoard"",
    ""maps"": [
        {
            ""name"": ""MainAction"",
            ""id"": ""95d654c8-f5d7-4275-8c74-bcb741a4ae56"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""4623e7e5-4fb5-4960-8531-b326b93d450a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b0d514c9-e50f-4cc6-9d74-7560632c4c8a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainAction
        m_MainAction = asset.FindActionMap("MainAction", throwIfNotFound: true);
        m_MainAction_Move = m_MainAction.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainAction
    private readonly InputActionMap m_MainAction;
    private List<IMainActionActions> m_MainActionActionsCallbackInterfaces = new List<IMainActionActions>();
    private readonly InputAction m_MainAction_Move;
    public struct MainActionActions
    {
        private @PlayerMovementInputWithoutKeyBoard m_Wrapper;
        public MainActionActions(@PlayerMovementInputWithoutKeyBoard wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_MainAction_Move;
        public InputActionMap Get() { return m_Wrapper.m_MainAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActionActions set) { return set.Get(); }
        public void AddCallbacks(IMainActionActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IMainActionActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IMainActionActions instance)
        {
            if (m_Wrapper.m_MainActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainActionActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainActionActions @MainAction => new MainActionActions(this);
    public interface IMainActionActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
